---
title: "Exploring R4ds"
output: html_notebook
---

library(tidyverse)
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy, size = class))


ggplot(data = diamonds) +
 geom_histogram(mapping = aes(x = carat), binwidth = 0.5)

ggplot(data = smaller, mapping = aes(x = carat)) +
 geom_histogram(binwidth = 0.1)

ggplot(data = faithful, mapping = aes(x = eruptions)) +
 geom_histogram(binwidth = 0.25)

ggplot(data = faithful, mapping = aes(x = eruptions)) +
 geom_histogram(binwidth = 0.25)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point() +
 geom_smooth()
ggplot() +
 geom_point(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 ) +
 geom_smooth(
 data = mpg,
 mapping = aes(x = displ, y = hwy)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point() +
 geom_smooth()
ggplot() +
 geom_point(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 
 geom_smooth(
 data = mpg,
 mapping = aes(x = displ, y = hwy)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point() +
 geom_smooth()
ggplot() +
 geom_point(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 ) +
 geom_smooth(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 
 ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point() +
 geom_smooth()
ggplot() +
 geom_point(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 ) +
 geom_smooth(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 
 ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point() +
 geom_smooth()
ggplot() +
 geom_point(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 ) +
 geom_smooth(
 data = mpg,
 mapping = aes(x = displ, y = hwy)
 
 ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy)) +
 facet_grid(drv ~ cyl)
 
 
 